language: cpp

os: osx

matrix:
    include:
        - osx_image: xcode9.3
        - osx_image: xcode9.2

install:
    - brew uninstall --ignore-dependencies boost

script:
    - brew install --build-bottle Formula/sdl2.rb
    - brew bottle sdl2

    - brew install --build-bottle Formula/boost.rb
    - brew bottle boost

    - brew install --build-bottle Formula/yaml-cpp.rb
    - brew bottle yaml-cpp

after_success:
    - for f in *.tar.gz ; do curl --progress-bar --upload-file $f https://transfer.sh/$f -o link && cat link ; done
